export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss', '@vueuse/nuxt'],
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
  },
  app: {
    baseURL: process.env.NUXT_APP_BASE_URL || '/',
    head: {
      htmlAttrs: { lang: 'sk' },
      title: 'Wellow – Vôňa, ktorá prúdi.',
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        { rel: 'apple-touch-icon', href: '/favicon.svg' },
        { rel: 'canonical', href: 'https://www.wellow.sk/' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
      ],
      meta: [
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'robots', content: 'index, follow' },
        { name: 'theme-color', content: '#131311' },
        { name: 'description', content: 'Wellow prináša prémiovú vôňu tam, kde prirodzene prúdi vzduch. Slovenský produkt navrhnutý pre bytové klimatizácie.' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Wellow' },
        { property: 'og:url', content: 'https://www.wellow.sk/' },
        { property: 'og:title', content: 'Wellow – Vôňa, ktorá prúdi.' },
        { property: 'og:description', content: 'Wellow prináša prémiovú vôňu tam, kde prirodzene prúdi vzduch. Slovenský produkt navrhnutý pre bytové klimatizácie.' },
        { property: 'og:image', content: 'https://www.wellow.sk/pngs/new_frontal_black.png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:locale', content: 'sk_SK' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: 'Wellow – Vôňa, ktorá prúdi.' },
        { name: 'twitter:description', content: 'Wellow prináša prémiovú vôňu tam, kde prirodzene prúdi vzduch. Slovenský produkt navrhnutý pre bytové klimatizácie.' },
        { name: 'twitter:image', content: 'https://www.wellow.sk/pngs/new_frontal_black.png' },
      ],
      script: [
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Organization',
            name: 'Wellow',
            url: 'https://www.wellow.sk',
            logo: 'https://www.wellow.sk/favicon.svg',
            description: 'Prémiové vône navrhnuté pre bytové klimatizácie. Slovenský produkt.',
            foundingLocation: { '@type': 'Country', name: 'Slovakia' },
            sameAs: ['https://www.wellow.sk'],
          }),
        },
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'FAQPage',
            mainEntity: [
              { '@type': 'Question', name: 'Ako dlho vydrží vôňa?', acceptedAnswer: { '@type': 'Answer', text: 'Pri bežnom používaní klimatizácie vydrží vôňa približne 30 dní. Závisí od intenzity používania klimatizácie a prietoku vzduchu.' } },
              { '@type': 'Question', name: 'Zmestí sa Wellow do klimatizácie?', acceptedAnswer: { '@type': 'Answer', text: 'Áno. Wellow je navrhnutý pre nástenné klimatizácie a zároveň je kompatibilný aj s väčšinou iných typov klimatizácií.' } },
              { '@type': 'Question', name: 'Ovplyvní Wellow výkon klimatizácie?', acceptedAnswer: { '@type': 'Answer', text: 'Nie. Produkt je navrhnutý tak, aby neobmedzoval prúdenie vzduchu ani funkčnosť klimatizácie.' } },
              { '@type': 'Question', name: 'Čo ak chcem priestor prevoňať bez chladenia alebo kúrenia?', acceptedAnswer: { '@type': 'Answer', text: 'Stačí zapnúť klimatizáciu v režime ventilácie. Prúd vzduchu prirodzene rozptýli vôňu do priestoru bez potreby chladenia alebo vykurovania.' } },
              { '@type': 'Question', name: 'Čo ak už nechcem, aby klimatizácia ďalej rozptyľovala vôňu?', acceptedAnswer: { '@type': 'Answer', text: 'Wellow je uchytený pomocou magnetu, takže ho môžete jednoducho vybrať alebo odložiť na čas, keď nechcete vôňu používať.' } },
              { '@type': 'Question', name: 'Sú vône bezpečné?', acceptedAnswer: { '@type': 'Answer', text: 'Áno. Použité vonné zložky sú registrované v Európskej chemickej agentúre (ECHA) a spĺňajú požiadavky pre bezpečné používanie v interiéri.' } },
              { '@type': 'Question', name: 'Dá sa kazeta znovu naplniť?', acceptedAnswer: { '@type': 'Answer', text: 'Aktuálna verzia nie je rozoberateľná. Pracujeme však na budúcej verzii s možnosťou výmeny náplne.' } },
            ],
          }),
        },
      ],
    },
  },
  nitro: {
    preset: 'static',
  },
  ssr: true,
})
